version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=wp_user
      - POSTGRES_PASSWORD=wp_password
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=events
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: